Solution of Exception Home Task

Home Task-1 Solution:
---------------------------------------------------------------------------------------

import java.util.*;

public class ExceptionTest {
    public static void main(String args[])  {

        Scanner input = new Scanner(System.in);

        int count=0;
      int sum=0;

        while(count<5)
        {
            System.out.println("Please give an integer number: ");
            try {
                int number = input.nextInt(); //throws Exception
                count++;
                sum+=number;
            }
            catch(InputMismatchException e)
            {
                System.out.println(e);

                // For taking the wrong previous data and removing it from the buffer
                String wrongInput = input.nextLine();

               // System.out.println("S = "+wrongInput);

            }
        }
        System.out.println("The sum is:"+sum);

    }


}

//------------------------------------------------------------------------------------------------------------


HOme Task-2 Solution:
--------------------------------------------------------------------------------------
//This is the ExceptionTest.java file 

import java.util.*;

public class ExceptionTest {
    public static void main(String args[])  {

        try {
            int result = readInteger();
            System.out.println("User successfully input the number: "+ result);
        }
        catch(EitaIntegerNoiException e)
        {
            System.out.println(e); //here e.toString() method, inside the EitaIntegerNoiException class.. is called
            e.printError();
        }


    }

    static int readInteger( ) throws EitaIntegerNoiException
    {
        Scanner k = new Scanner(System.in);
        String s;
        int answer;
        //Take the input from the user in s

        s = k.nextLine();


        if (s.contains(".")) //checking whether the input String s has '.' character
        {

            throw new EitaIntegerNoiException(s); //create exception and throw it


        }else{
             //Here we come when the input has no '.' character
            //So convert the String 's' into integer answer
            
             answer = Integer.parseInt(s);

        }

        return answer;

    }


}


//--------------------------EitaIntegerNoiException.java ---------------------------------------------------

public class EitaIntegerNoiException extends Exception{

    private String msg;

    EitaIntegerNoiException(String s)
    {
        msg = s;
    }

    public String toString(){
        return "EitaIntegerNoiException is thrown because of the input from user:" + msg ;
    }

    public void printError(){
        System.out.println("The argument: " +  msg + " is not a integer!!");
    }
}

//--------------------------------------------------------------------------------------